name: Push to fsYara

on:
  push:
    branches:
      - STI-*
      - master

jobs:
  update-fsYara-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: python setup
      uses: actions/setup-python@v3

    # plyara and yara installation must happen before the pre commit execution (compile.py requires it)
    - name: Yara installation
      run: |
        pip3 install plyara
        sudo apt install yara

    - name: pre-commit
      uses: pre-commit/action@v3.0.1

      # default verbosity is 30 (Critical, Error, Warning) 
      # use -v / --verbose to increase verbosity to info (-v -v to switch on Debug mode)
    - name: Yara hardening
      run: |
        python3 tools/ci/harden_yara.py low_hit
      
    # Running pre-commit after hardening to make sure, that the process did not break any Yara rule
    - name: pre-commit after hardening
      uses: pre-commit/action@v3.0.1

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.FSYARA_DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no"
        # eval `ssh-agent -s`
        # ssh-add your_key
        rm -rf target-repo
        # git clone https://github.com/filescanio/fsYara-test.git target-repo
        git remote add target "git@github.com:filescanio/fsYara-test.git"
        git clone git@github.com:filescanio/fsYara-test.git target-repo

    - name: Clone Target Repository
      # if: github.ref == 'refs/heads/master'
      # env:
      #   TARGET_REPO_URL: https://github.com/filescanio/fsYara-test.git
      #   TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
      # run: |
      #   rm -rf target-repo
      #   git clone https://$TARGET_REPO_PAT@github.com/filescanio/fsYara-test.git target-repo
      run: |
        rm -rf target-repo
        # git clone https://github.com/filescanio/fsYara-test.git target-repo
        git remote add target "git@github.com:filescanio/fsYara-test.git"
        git clone git@github.com:filescanio/fsYara-test.git target-repo

    - name: Commit and Push
      # if: github.ref == 'refs/heads/master'
      # env:
      #   TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
      run: |
        find ./target-repo -mindepth 1 ! -regex '^./target-repo/.git\(/.*\)?' -delete
        rsync -avq --exclude=".*" --exclude="target-repo" ./ target-repo
        cd target-repo
        git config user.email "zsolt.major@opswat.com"
        git config user.name "zsoltmajoropswat"
        git add .
        git commit -m "Automated update from source repository"
        git push --set-upstream origin